Feature/main cmdline app
RidgeRun/ti-edge-ai-demos pull request #23
Opened 2021-08-19 01:34 UTC by dchvs

2021-08-19 16:05 UTC, emmadrigal requested changes

2021-08-19 16:05 UTC, emmadrigal commented on rr/ai/ai_manager_mock.py
> +#            img, inference_results)
Don't commit dirty code

2021-08-19 16:05 UTC, emmadrigal commented on rr/ai/ai_manager_mock.py
> +        image2 = GstImage(w, h, fmt, sample2, image.get_media())
Are you using `image2`?

2021-08-19 16:05 UTC, emmadrigal commented on rr/gstreamer/gst_media.py
> +                (candidate for candidate in all_triggers if trigger == candidate._name),
`_name` is supposed to be private

2021-08-19 16:07 UTC, dchvs commented on rr/ai/ai_manager_mock.py
> +        image2 = GstImage(w, h, fmt, sample2, image.get_media())
I have deleted this mocked AIManager!

2021-08-19 16:09 UTC, dchvs commented on rr/ai/ai_manager_mock.py
> +#            img, inference_results)
Thanks. Also, I have deleted this mocking file as we put the real AIManager to work within this PR.

2021-08-23 17:02 UTC, emmadrigal approved these changes

2021-08-23 17:14 UTC, merged