Feature/add onnewtensor callback flow
RidgeRun/ti-edge-ai-demos pull request #29
Opened 2021-09-24 00:31 UTC by dchvs

2021-09-27 14:53 UTC, emmadrigal requested changes

2021-09-27 14:53 UTC, emmadrigal commented on rr/gstreamer/gst_media.py
> +        timeout = 5000000000  # 5 seconds in nanoseconds
Why change this back?

2021-09-27 14:53 UTC, emmadrigal commented on rr/gstreamer/gst_media.py
> +model = '/opt/model_zoo/TFL-OD-2000-ssd-mobV1-coco-mlperf-300x300/'
Is this ok as a fixed value? shouldn't we read this from a config file?

2021-09-27 14:53 UTC, emmadrigal commented on rr/gstreamer/gst_media.py
> +            "tensor-width"), tensor_caps.get_structure(0).get_value("tensor-height"), tensor_caps.get_structure(0).get_value("tensor-format"))
Line is too long

2021-09-27 14:53 UTC, emmadrigal commented on rr/gstreamer/media_manager.py
> +                self._Dict[key].install_tensor_callback(callback[key])
Use 
```
for key, values in self._Dict.items()
```

2021-09-29 16:38 UTC, michaelgruner requested changes

2021-09-29 16:38 UTC, michaelgruner commented on rr/display/display_manager.py
> +        desc += " ! videoscale ! kmssink force-modesetting=true sync=false async=false qos=false "
Why do we need this?

2021-09-29 16:38 UTC, michaelgruner commented on rr/gstreamer/gst_media.py
> +
No, please pass the model and the params to the make method if possible. Saving stuff in the class struct is very dangerous.

2021-09-29 16:38 UTC, michaelgruner commented on rr/gstreamer/gst_media.py
> +            tensor_data_layout,
This will break a lot of tests. Please check tests before submitting PRs. I would avoid extending the image with this. You're not using for anything.

2021-10-04 14:52 UTC, emmadrigal approved these changes

2021-10-12 21:07 UTC, merged