Feature/config loader
RidgeRun/ti-edge-ai-demos pull request #7
Opened 2021-07-13 19:13 UTC by Solzc

2021-07-13 19:45 UTC, emmadrigal requested changes

2021-07-13 19:45 UTC, emmadrigal commented on rr/config/app_validator.py
> +class AppValidatortError(RuntimeError):
This whole document is missing docstring

2021-07-13 19:45 UTC, emmadrigal commented on rr/config/config_loader.py
> +class ConfigLoader:
Missing docstring

2021-07-13 19:45 UTC, emmadrigal commented on rr/config/app_validator.py
> +    def validate_streams(self, cfg):
Other than `validate` all the functions in this class don't require `self`, move them to functions

2021-07-13 19:45 UTC, emmadrigal commented on rr/config/yaml_format.py
> +class YamlFormatError(RuntimeError):
Missing docstring

2021-07-13 19:45 UTC, emmadrigal commented on tests/config/test_app_validator.py
> +        cfg_obj3 = {'streams': 'test'}
Try to use more representative names. Something like:
```
cfg_good =
cfg_missing_stream =
cfg_invalid_stream =
```

2021-07-13 19:45 UTC, emmadrigal commented on tests/config/test_app_validator.py
> +
Please add a test with `cfg_empty = None`

2021-07-13 19:45 UTC, emmadrigal commented on tests/config/test_app_validator.py
> +        cfg_obj1 = {'streams': [
Use more representative names

2021-07-13 19:45 UTC, emmadrigal commented on tests/config/test_app_validator.py
> +        cfg_obj1 = {'streams': [
Use more representative names

2021-07-13 19:45 UTC, emmadrigal commented on tests/config/test_app_validator.py
> +        cfg_obj1 = {'streams': [
Use more representative names

2021-07-13 19:45 UTC, emmadrigal commented on rr/config/app_validator.py
> +                raise AppValidatortError("Invalid triggers format")
The message could be more informative.
```
Invalid id format, should be str
...
Invalid triggers format, should be a list
```

2021-07-13 19:45 UTC, emmadrigal commented on rr/config/app_validator.py
> +                        "Invalid trigger format in streams triggers")
```Invalid trigger format in streams triggers, should be string```

2021-07-13 19:45 UTC, emmadrigal commented on rr/config/app_validator.py
> +                raise AppValidatortError("Invalid threshold format")
Add more info to error message `should be ...`

2021-07-13 19:45 UTC, emmadrigal commented on rr/config/app_validator.py
> +            raise AppValidatortError("Invalid location format in action")
Add more info to error message about correct type

2021-07-13 19:45 UTC, emmadrigal commented on tests/config/test_app_validator.py
> +        self.assertEqual(None, validate)
Good testing! it seems you are covering all if not most cases :+1:

2021-07-13 19:45 UTC, emmadrigal commented on tests/config/test_yaml.yaml
> +test: 10
Add newline at the end of the file

2021-07-13 19:45 UTC, emmadrigal commented on rr/config/app_validator.py
> +                raise AppValidatortError("Invalid triggers format")
Maybe even add the received type:
`"received a " stream_id.type() " expected a str"`
or
`stream_id "is a " stream_id.type() " expected a str"`

2021-07-13 19:45 UTC, emmadrigal commented on tests/config/test_yaml_invalid.yaml
> + - three (invalid indentation)
Add newline at the end of the file

2021-07-14 00:00 UTC, michaelgruner requested changes

2021-07-14 00:00 UTC, michaelgruner commented on rr/config/app_validator.py
> +            raise AppValidatortError("Invalid streams format")
Be consistent with the message formatting. Are you starting with upper case or lower case?

2021-07-14 00:00 UTC, michaelgruner commented on rr/config/app_validator.py
> +            raise AppValidatortError("Invalid streams format")
Also, this message could be way more helpful. For example, consider something like: `found streams field, but it is not a list.`

2021-07-14 00:00 UTC, michaelgruner commented on rr/config/app_validator.py
> +            raise AppValidatortError("Invalid streams format")
chain to the parent exception

2021-07-14 00:00 UTC, michaelgruner commented on rr/config/app_validator.py
> +        if (not isinstance(streams, list)):
There is no need for parenthesis in python.

2021-07-14 00:00 UTC, michaelgruner commented on rr/config/app_validator.py
> +                stream_id = stream['id']
Note the code replication. Keep your code [dry](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). You have the same pattern everywhere:

```python
try:
  value = dict[key]
except KeyError as e:
  raise AppValidatortError (key_err_msg) from e

if not isinstance(value, expected_type)):
  raise AppValidatortError(type_err_msg)
```
See how it could be factored out?

2021-07-14 00:00 UTC, michaelgruner commented on rr/config/app_validator.py
> +            for trigger in stream_triggers:
How do we validate if the trigger actually exists?

2021-07-14 00:00 UTC, michaelgruner commented on rr/config/app_validator.py
> +                trigger_action = trigger['action']
Validate the action actually exists

2021-07-14 00:00 UTC, michaelgruner commented on rr/config/app_validator.py
> +                trigger_filters = trigger['filters']
Validate that the filter actually exists.

2021-07-14 00:00 UTC, michaelgruner commented on rr/config/app_validator.py
> +        self.validate_streams(cfg)
In other modules you prepend private methods with a `_` (which is a correct python standard). Please be consistent with the coding standard.

2021-07-14 00:00 UTC, michaelgruner commented on rr/config/config_loader.py
> +class AppConfigLoader:
Do not mix these. What if you need a new loader? the ConfigLoader is generic, while the AppConfigLoader is a specific facade.

2021-07-14 19:33 UTC, michaelgruner approved these changes
Approved with a couple of comments. Please attend them before merging.

2021-07-14 19:33 UTC, michaelgruner commented on rr/config/app_validator.py
> +                filt, filters, "Trigger has a not defined filter")
It would be helpful if you said which one is not defined. For example `Triggers attempts to use the \"%s\" filter, but it is not defined anywhere`.

2021-07-14 19:33 UTC, michaelgruner commented on rr/config/app_validator.py
> +            "Trigger has a not defined action")
Same here.

2021-07-14 19:40 UTC, emmadrigal approved these changes

2021-07-14 19:40 UTC, emmadrigal commented on rr/config/app_config_loader.py
> +    Class that serves as the Apo Config facade
Typo `App`

2021-07-14 19:40 UTC, emmadrigal commented on rr/config/app_validator.py
> +    """Validates the avtions field of the configuration object
Typo `actions`

2021-07-14 21:47 UTC, merged